spring:
    datasource:
        username: root
        password: 1qaz!QAZ
        url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
    mapper-locations: classpath:mapper/*